
- name: Deploy DNS
  hosts: helm
  roles:
    - dns

- name: Setup Workers to use new DNS
  hosts: workers
  tasks:
    - include_role:
        name: k3s-worker
        tasks_from: resolv
  vars:
    dns_ip: "{{ hostvars[groups['helm'][0]]['hosted_dns'] }}"
