
- name: Helm setup on all helm servers
  hosts: localhost
  tasks:
  - name: Helm
    include_role:
      name: common
      tasks_from: helm

- name: Setup DNS
  hosts: localhost
  roles:
    - dns
