
- name: Setup Registry
  hosts: helm
  roles:
    - registry

- name: Setup Registy k3s config
  hosts: workers
  tasks:
    - include_role:
        name: k3s-worker
        tasks_from: registries
  tags:
    - registry

- name: Deploy Internal Containers
  hosts: build
  tasks:
    - include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ee-build
        docker_template: build.Dockerfile
      # with_items:
