
- name: Setup Registry
  hosts: helm
  roles:
    - registry

- name: Setup Registy k3s config
  hosts: workers
  tasks:
    - include_role:
        name: k3s-worker
        tasks_from: registries
  tags:
    - registry

- name: Deploy Internal Containers
  hosts: build
  tasks:

    - name: Python Base
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: python/base
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/python-base-image.git

    - name: Python Builder
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: python/builder
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/python-builder-image.git
        build_args:
          CONTAINER_IMAGE: "{{ registry_host }}/python/base"

    - name: Ansible Runner
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ansible/runner
        container_dockerfile: Dockerfile
        container_source: https://github.com/ansible/ansible-runner.git
        build_args:
          PYTHON_BASE_IMAGE: "{{ registry_host }}/python/base"
          PYTHON_BUILDER_IMAGE: "{{ registry_host }}/python/builder"

    - name: Ansible Builder
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ansible/builder
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/awx-ee.git
        build_args:
          PYTHON_BASE_IMAGE: "{{ registry_host }}/python/base"
          PYTHON_BUILDER_IMAGE: "{{ registry_host }}/python/builder"

    - name: AWX Execution Environment
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: awx/ee
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/awx-ee.git
        build_args:
          EE_BASE_IMAGE: "{{ registry_host }}/ansible/runner"
          EE_BUILDER_IMAGE: "{{ registry_host }}/ansible/builder"

    - include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ee-build
        docker_template: build.Dockerfile
      # with_items:
