
- name: Setup Registry
  hosts: localhost
  roles:
    - registry

- name: Setup Registy k3s config
  hosts: workers
  tasks:
    - include_role:
        name: k3s-worker
        tasks_from: registries
  tags:
    - registry
