all:
  children:
    master:
      hosts:
        rpi-master.local:
          ansible_host: 192.168.0.11

    workers:
      hosts:
        worker-01.local:
          ansible_host: 192.168.0.21
        worker-02.local:
          ansible_host: 192.168.0.22
        worker-03.local:
          ansible_host: 192.168.0.23
        worker-04.local:
          ansible_host: 192.168.0.24
        worker-05.local:
          ansible_host: 192.168.0.25

    helm:
      hosts:
        rpi-master.local:

    build:
      hosts:
        rpi-master.local:

  vars:
    ansible_user: pi

    base_dns: contoso.local
    dns_resource_name: internal-dns
    dns_namespace: coredns

    ingress_name: contoso-ingress
    ingress_namespace: ingress

    pihole_host: pihole.contoso.local
