- name: AWX Namespace
  include_role:
    name: kube
    tasks_from: namespace
  vars:
    namespace: awx

- name: Install AWX Operator
  include_role:
    name: common
    tasks_from: apply-file
  vars:
    manifest_url: https://raw.githubusercontent.com/ansible/awx-operator/{{ awx_version }}/deploy/awx-operator.yaml
    awx_version: "0.12.0"
    manifest_file_path: temp/awx-operator.yml
    namespace: default
