# sudo groupadd docker
- name: Group {{ group }} Exists
  become: yes
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

# sudo usermod -aG docker root
- name: User {{ user }} is added to {{ group }}
  become: yes
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    append: yes
