- name: Python SetupTools
  ansible.builtin.packages: 
    name: python-setuptools

- name: Install Python packages
  ansible.builtin.pip:
    name: "{{ package }}"
    virtualenv: "{{ venv_path | default(omit) }}"
  with_items: "{{ packages | default([]) }}"
  loop_control:
    loop_var: package
