- name: Add helm Nginx repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"
  delegate_to: "{{ HELM_DELEGATE }}"
  run_once: True
  tags: setup

- name: Install Nginx Chart
  kubernetes.core.helm:
    name: internal-ingress
    chart_ref: ingress-nginx/ingress-nginx
    values: "{{ lookup('template', 'ingress-values.yml') | from_yaml }}"
    release_namespace: "{{ ingress_namespace }}"
    create_namespace: true
  delegate_to: "{{ HELM_DELEGATE }}"
  tags: install
