- name: LoadBalancer
  block:
    - name: MetalB Namespace
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'metalb-namespace.yml') | from_yaml }}"

    - name: MetalB Config
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'metalb-config.yml') | from_yaml }}"

    - name: Get Newest Metalb Manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml
        dest: /tmp/metalb-core.yml
        mode: '0664'
      register: manifest

    - name: MetalB Core System
      kubernetes.core.k8s:
        src: "{{ manifest.dest }}"
  tags: install

- name: Internal Ingress
  block:
    - name: Add helm nginx repo
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Install Nginx Chart for internal controller
      kubernetes.core.helm:
        name: internal-ingress
        chart_ref: ingress-nginx/ingress-nginx
        values: "{{ lookup('template', 'files/internal-values.yml') | from_yaml }}"
        release_namespace: internal-ingress
        create_namespace: true
  tags: install
        
- name: External Ingress
  block:
    - name: Add helm nginx repo
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Install Nginx Chart for external controller
      kubernetes.core.helm:
        name: external-ingress
        chart_ref: ingress-nginx/ingress-nginx
        values: "{{ lookup('template', 'files/external-values.yml') | from_yaml }}"
        release_namespace: external-ingress
        create_namespace: true
  when: external_ingress is true
  tags: install