# Variables
- name: Set resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    search_string: "domain"
    line: "domain {{ base_dns }}"
  become: yes

- name: Set resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ dns_ip }}"
  become: yes
