
- name: Deploy Internal Containers
  hosts: build
  tags:
    - container-build
  tasks:
    - name: Python Base
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: python/base
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/python-base-image.git
      tags: python-base

    - name: Python Builder
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: python/builder
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/python-builder-image.git
        build_args:
          CONTAINER_IMAGE: "{{ registry_host }}/python/base"
      tags: python-builder

    - name: Ansible Runner
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ansible/runner
        container_dockerfile: Dockerfile
        container_source: https://github.com/ansible/ansible-runner.git
        build_args:
          PYTHON_BASE_IMAGE: "{{ registry_host }}/python/base"
          PYTHON_BUILDER_IMAGE: "{{ registry_host }}/python/builder"
      tags: ansible-runner

    - name: Ansible Builder
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ansible/builder
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/ansible-builder.git
        build_args:
          PYTHON_BASE_IMAGE: "{{ registry_host }}/python/base"
          PYTHON_BUILDER_IMAGE: "{{ registry_host }}/python/builder"
      tags: ansible-builder

    # Build Custom Runner to usefor the EE
    - name: Ansible Custom Runner
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ansible/custom/runner
        docker_template: make.Dockerfile
        build_args:
          EE_BASE_IMAGE: "{{ registry_host }}/ansible/runner"
      tags: ansible-custom-runner

    # Build Custom Runner to usefor the EE
    - name: Ansible Custom Builder
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: ansible/custom/builder
        docker_template: make.builder.Dockerfile
        build_args:
          EE_BASE_IMAGE: "{{ registry_host }}/ansible/builder"
      tags: ansible-custom-builder

    - name: AWX Execution Environment
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: awx/ee
        container_dockerfile: Containerfile
        container_source: https://github.com/ansible/awx-ee.git
        build_args:
          EE_BASE_IMAGE: "{{ registry_host }}/ansible/custom/runner"
          EE_BUILDER_IMAGE: "{{ registry_host }}/ansible/custom/builder"
      tags: awx-ee

    # - name: AWX Custom Execution Environment
    #   include_role:
    #     name: docker
    #     tasks_from: build
    #   vars:
    #     container_name: awx/custom/ee
    #     docker_template: build.Dockerfile
    #     build_args:
    #       EE_BASE_IMAGE: "{{ registry_host }}/awx/ee"
    #   tags: awx-custom-ee
    - name: AWX Operator
      include_role:
        name: docker
        tasks_from: build
      vars:
        container_name: awx/operator
        container_dockerfile: Dockerfile
        container_source: https://github.com/ansible/awx-operator.git
        # container_source: https://github.com/amacc/awx-operator.git
        # build_args:
        #   OPERATOR_BASE_IMAGE: "{{ registry_host }}/awx/ee"
      tags: awx-operator

        # container_source: https://github.com/ansible/awx-operator.git


# - name: Install AWX Operator

#   hosts: localhost
#   roles:
#     - awx
