
- name: Deploy DNS
  hosts: dns
  roles:
    - dns

- name: Setup Workers to use new DNS
  hosts: workers
  tasks:
    - name: Setup resolv.conf on the worker nodes.
      include_role:
        name: k3s-worker
        tasks_from: resolve
  vars:
    dns_ip: "{{ hostvars[groups['helm'][0]]['hosted_dns_ip'] }}"
